// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyStrategy(arg1, arg2) {
  return window['go']['main']['App']['ApplyStrategy'](arg1, arg2);
}

export function FetchAndApplyStrategy(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['FetchAndApplyStrategy'](arg1, arg2, arg3, arg4, arg5);
}

export function FetchCandles(arg1, arg2, arg3) {
  return window['go']['main']['App']['FetchCandles'](arg1, arg2, arg3);
}

export function FetchCandlesBefore(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['FetchCandlesBefore'](arg1, arg2, arg3, arg4);
}

export function GetRunningStrategies() {
  return window['go']['main']['App']['GetRunningStrategies']();
}

export function InvalidateCache() {
  return window['go']['main']['App']['InvalidateCache']();
}

export function InvalidateCacheForSymbol(arg1) {
  return window['go']['main']['App']['InvalidateCacheForSymbol'](arg1);
}

export function IsRedisConnected() {
  return window['go']['main']['App']['IsRedisConnected']();
}

export function StartLiveStrategy(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['StartLiveStrategy'](arg1, arg2, arg3, arg4, arg5);
}

export function StopLiveStrategy(arg1) {
  return window['go']['main']['App']['StopLiveStrategy'](arg1);
}

export function StrategyRun(arg1) {
  return window['go']['main']['App']['StrategyRun'](arg1);
}
