// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseStrategyPosition(arg1) {
  return window['go']['main']['App']['CloseStrategyPosition'](arg1);
}

export function FetchCandles(arg1, arg2, arg3) {
  return window['go']['main']['App']['FetchCandles'](arg1, arg2, arg3);
}

export function FetchCandlesBefore(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['FetchCandlesBefore'](arg1, arg2, arg3, arg4);
}

export function GetActivePositions() {
  return window['go']['main']['App']['GetActivePositions']();
}

export function GetPortfolioSummary() {
  return window['go']['main']['App']['GetPortfolioSummary']();
}

export function GetRunningStrategies() {
  return window['go']['main']['App']['GetRunningStrategies']();
}

export function GetWalletAddress() {
  return window['go']['main']['App']['GetWalletAddress']();
}

export function InvalidateCache() {
  return window['go']['main']['App']['InvalidateCache']();
}

export function InvalidateCacheForSymbol(arg1) {
  return window['go']['main']['App']['InvalidateCacheForSymbol'](arg1);
}

export function StopLiveStrategy(arg1) {
  return window['go']['main']['App']['StopLiveStrategy'](arg1);
}

export function StrategyBacktest(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['StrategyBacktest'](arg1, arg2, arg3, arg4);
}

export function StrategyRun(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['StrategyRun'](arg1, arg2, arg3, arg4);
}
