// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {hyperliquid} from '../models';

export function ApplyStrategy(arg1:string,arg2:Record<string, any>):Promise<void>;

export function FetchAndApplyStrategy(arg1:string,arg2:string,arg3:number,arg4:string,arg5:Record<string, any>):Promise<main.StrategyOutputV2>;

export function FetchCandles(arg1:string,arg2:string,arg3:number):Promise<hyperliquid.Candles>;

export function FetchCandlesBefore(arg1:string,arg2:string,arg3:number,arg4:number):Promise<hyperliquid.Candles>;

export function GetActivePositions():Promise<Array<main.ActivePosition>>;

export function GetConfig():Promise<main.Config>;

export function GetPortfolioSummary():Promise<main.PortfolioSummary>;

export function GetRunningStrategies():Promise<Array<main.StrategyInstance>>;

export function GetWalletAddress():Promise<string>;

export function InvalidateCache():Promise<void>;

export function InvalidateCacheForSymbol(arg1:string):Promise<void>;

export function IsRedisConnected():Promise<boolean>;

export function SetConfigURL(arg1:string):Promise<void>;

export function SpotBuy(arg1:string,arg2:number):Promise<main.OrderResponse>;

export function SpotSell(arg1:string,arg2:number):Promise<main.OrderResponse>;

export function StartLiveStrategy(arg1:string,arg2:string,arg3:Record<string, any>,arg4:string,arg5:string):Promise<void>;

export function StopLiveStrategy(arg1:string):Promise<void>;

export function StrategyRun(arg1:hyperliquid.Candles):Promise<main.StrategyOutputV2>;
