// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {hyperliquid} from '../models';
import {main} from '../models';

export function CloseStrategyPosition(arg1:string):Promise<void>;

export function FetchCandles(arg1:string,arg2:string,arg3:number):Promise<hyperliquid.Candles>;

export function FetchCandlesBefore(arg1:string,arg2:string,arg3:number,arg4:number):Promise<hyperliquid.Candles>;

export function GetActivePositions():Promise<Array<main.ActivePosition>>;

export function GetPortfolioSummary():Promise<main.PortfolioSummary>;

export function GetRunningStrategies():Promise<Array<main.MaxTrendPointsStrategy>>;

export function GetWalletAddress():Promise<string>;

export function InvalidateCache():Promise<void>;

export function InvalidateCacheForSymbol(arg1:string):Promise<void>;

export function StopLiveStrategy(arg1:string):Promise<void>;

export function StrategyBacktest(arg1:string,arg2:string,arg3:number,arg4:Record<string, any>):Promise<main.BacktestOutput>;

export function StrategyRun(arg1:string,arg2:string,arg3:string,arg4:Record<string, any>):Promise<void>;
