// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {hyperliquid} from '../models';

export function ApplyStrategy(arg1:string,arg2:Record<string, any>):Promise<void>;

export function ClosePosition(arg1:main.ClosePositionRequest):Promise<main.OrderResponse>;

export function ConnectWallet(arg1:string):Promise<void>;

export function FetchAndApplyStrategy(arg1:string,arg2:string,arg3:number,arg4:string,arg5:Record<string, any>):Promise<main.StrategyOutputV2>;

export function FetchCandles(arg1:string,arg2:string,arg3:number):Promise<hyperliquid.Candles>;

export function FetchCandlesBefore(arg1:string,arg2:string,arg3:number,arg4:number):Promise<hyperliquid.Candles>;

export function GetActivePositions():Promise<Array<main.ActivePosition>>;

export function GetPortfolioSummary():Promise<main.PortfolioSummary>;

export function GetRunningStrategies():Promise<Array<main.StrategyInstance>>;

export function GetWalletAddress():Promise<string>;

export function IsWalletConnected():Promise<boolean>;

export function OpenLongPosition(arg1:string,arg2:number,arg3:number,arg4:string):Promise<main.OrderResponse>;

export function OpenShortPosition(arg1:string,arg2:number,arg3:number,arg4:string):Promise<main.OrderResponse>;

export function OpenTrade(arg1:main.OrderRequest):Promise<main.OrderResponse>;

export function StartLiveStrategy(arg1:string,arg2:string,arg3:Record<string, any>,arg4:string,arg5:string):Promise<void>;

export function StopLiveStrategy(arg1:string):Promise<void>;

export function StrategyRun(arg1:hyperliquid.Candles):Promise<main.StrategyOutputV2>;
